CREATE TABLE Users(
Id INT PRIMARY KEY,
Username NVARCHAR(50) NOT NULL,
Email NVARCHAR(100)
);

CREATE TABLE Posts(
Id INT PRIMARY KEY,
Content NVARCHAR(200),
UserId INT,
FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE Likes(
Id INT PRIMARY KEY,
UserId INT,
PostId INT,
FOREIGN KEY(UserId) REFERENCES Users(Id),
FOREIGN KEY(PostId) REFERENCES Posts(Id)
);

